# Generated by Django 4.2.30 on 2026-04-20 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('receivable', 'Accounts Receivable'), ('bank', 'Bank Account'), ('stripe_clearing', 'Stripe Clearing')], max_length=20)),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(max_length=256, unique=True)),
                ('normalized_name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'counterparties',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=5)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('vat_number', models.CharField(blank=True, max_length=32, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('invoices', 'Invoices'), ('transactions', 'Transactions'), ('payout', 'Payout')], max_length=16)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('raw_content', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=32, unique=True)),
                ('type', models.CharField(choices=[('invoice', 'Invoice'), ('credit_note', 'Credit Note')], default='invoice', max_length=16)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('force_closed', 'Force Closed')], default='open', max_length=16)),
                ('force_close_note', models.TextField(blank=True, null=True)),
                ('force_closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reconciler.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='reconciler.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=16)),
                ('total_processed', models.PositiveIntegerField(default=0)),
                ('auto_matched_count', models.PositiveIntegerField(default=0)),
                ('needs_review_count', models.PositiveIntegerField(default=0)),
                ('skipped_locked_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('source_type', models.CharField(choices=[('bank', 'Bank'), ('payment_processor', 'Payment Processor'), ('crm', 'CRM'), ('erp', 'ERP'), ('manual', 'Manual')], max_length=32)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=32, unique=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('raw_counterparty', models.CharField(max_length=256)),
                ('structured_reference', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('reconciliation_status', models.CharField(choices=[('unprocessed', 'Unprocessed'), ('auto_matched', 'Auto Matched'), ('needs_review', 'Needs Review'), ('reconciled', 'Reconciled'), ('unrelated', 'Unrelated'), ('duplicate', 'Duplicate')], default='unprocessed', max_length=16)),
                ('locked_by_user', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='reconciler.counterparty')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reconciler.currency')),
                ('ingestion_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='reconciler.ingestionevent')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='reconciler.source')),
            ],
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('reviewer', 'Reviewer'), ('admin', 'Admin')], default='reviewer', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayoutLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(max_length=64, unique=True)),
                ('raw_invoice_id', models.CharField(blank=True, max_length=32, null=True)),
                ('customer_name', models.CharField(max_length=256)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('charge', 'Charge'), ('refund', 'Refund'), ('chargeback', 'Chargeback'), ('payout', 'Payout')], max_length=16)),
                ('ingestion_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_lines', to='reconciler.ingestionevent')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_lines', to='reconciler.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('match_type', models.CharField(choices=[('exact', 'Exact'), ('partial', 'Partial'), ('consolidated', 'Consolidated'), ('fx', 'FX'), ('credit_note', 'Credit Note'), ('payout', 'Payout'), ('noise', 'Noise'), ('duplicate', 'Duplicate'), ('prepayment', 'Prepayment')], max_length=16)),
                ('status', models.CharField(choices=[('auto_matched', 'Auto Matched'), ('needs_review', 'Needs Review'), ('confirmed', 'Confirmed'), ('manually_matched', 'Manually Matched'), ('rejected', 'Rejected'), ('unrelated', 'Unrelated')], max_length=20)),
                ('locked_by_user', models.BooleanField(default=False)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='reconciler.invoice')),
                ('payout_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='reconciler.payoutline')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_matches', to='reconciler.responsible')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='reconciler.transaction')),
            ],
            options={
                'verbose_name_plural': 'matches',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=512)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='reconciler.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='force_closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='force_closed_invoices', to='reconciler.responsible'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ingestion_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='reconciler.ingestionevent'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='reconciler.source'),
        ),
        migrations.AddField(
            model_name='ingestionevent',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_events', to='reconciler.source'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparties', to='reconciler.customer'),
        ),
        migrations.CreateModel(
            name='AccountEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entry_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='reconciler.account')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_entries', to='reconciler.invoice')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_entries', to='reconciler.match')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_entries', to='reconciler.transaction')),
            ],
            options={
                'verbose_name_plural': 'account entries',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reconciler.currency'),
        ),
        migrations.AddField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='reconciler.customer'),
        ),
        migrations.CreateModel(
            name='FXRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('date', models.DateField()),
                ('source', models.CharField(choices=[('fixed_demo', 'Fixed Demo'), ('ECB', 'ECB')], default='fixed_demo', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fx_base', to='reconciler.currency')),
                ('quote_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fx_quote', to='reconciler.currency')),
            ],
            options={
                'unique_together': {('base_currency', 'quote_currency', 'date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('customer', 'account_type', 'currency')},
        ),
    ]
