# Generated by Django 4.2.30 on 2026-04-20 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reconciler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('receivable', 'Accounts Receivable'), ('bank', 'Bank Account'), ('stripe_clearing', 'Stripe Clearing')], help_text='Role of this account in the double-entry pair.', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(help_text='Currency denomination of this account.', on_delete=django.db.models.deletion.PROTECT, to='reconciler.currency'),
        ),
        migrations.AlterField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(help_text='Customer this ledger account belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='reconciler.customer'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(help_text="Display name, e.g. 'Acme S.à r.l. — Receivable EUR'.", max_length=256),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='account',
            field=models.ForeignKey(help_text='Ledger account this entry is posted to.', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='reconciler.account'),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Absolute amount of this entry. Debit and credit entries always have the same amount.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='entry_type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], help_text='Debit increases the receivable; credit records the bank receipt.', max_length=8),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Invoice side of the double-entry pair.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_entries', to='reconciler.invoice'),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='match',
            field=models.ForeignKey(blank=True, help_text='Match that triggered this entry. Null if the entry was created by a non-match event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_entries', to='reconciler.match'),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='Transaction side of the double-entry pair.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_entries', to='reconciler.transaction'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='If this counterparty is known to correspond to a customer, link it here to improve match accuracy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparties', to='reconciler.customer'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='description',
            field=models.TextField(blank=True, help_text="Optional notes, e.g. 'law firm pooled client account'.", null=True),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='normalized_name',
            field=models.CharField(help_text='Cleaned version used for fuzzy matching; defaults to raw_name on creation.', max_length=256),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='raw_name',
            field=models.CharField(help_text='Counterparty name exactly as it appears in the bank export.', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(help_text='ISO 4217 three-letter code, e.g. EUR, USD, GBP.', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='decimal_places',
            field=models.PositiveSmallIntegerField(default=2, help_text='Number of decimal places used for amounts in this currency.'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive currencies are hidden from dropdowns but retained for historical records.'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(help_text='Full currency name, e.g. Euro.', max_length=64),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(help_text='Display symbol, e.g. €.', max_length=5),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, help_text='Registered office address.', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(help_text='Business-key from the source CRM, e.g. CUST-001.', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(help_text='Legal company name as it appears on invoices.', max_length=256),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vat_number',
            field=models.CharField(blank=True, help_text='EU VAT registration number, e.g. LU12345678.', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='fxrate',
            name='base_currency',
            field=models.ForeignKey(help_text='Currency being converted from.', on_delete=django.db.models.deletion.PROTECT, related_name='fx_base', to='reconciler.currency'),
        ),
        migrations.AlterField(
            model_name='fxrate',
            name='date',
            field=models.DateField(help_text='Date this rate applies to. Use the transaction date when converting amounts.'),
        ),
        migrations.AlterField(
            model_name='fxrate',
            name='quote_currency',
            field=models.ForeignKey(help_text='Currency being converted to.', on_delete=django.db.models.deletion.PROTECT, related_name='fx_quote', to='reconciler.currency'),
        ),
        migrations.AlterField(
            model_name='fxrate',
            name='rate',
            field=models.DecimalField(decimal_places=6, help_text='Units of quote currency per 1 unit of base currency.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='fxrate',
            name='source',
            field=models.CharField(choices=[('fixed_demo', 'Fixed Demo'), ('ECB', 'ECB')], default='fixed_demo', help_text='Provider of this rate.', max_length=16),
        ),
        migrations.AlterField(
            model_name='ingestionevent',
            name='error_message',
            field=models.TextField(blank=True, help_text='Exception message if status=failed; empty otherwise.', null=True),
        ),
        migrations.AlterField(
            model_name='ingestionevent',
            name='file_type',
            field=models.CharField(choices=[('invoices', 'Invoices'), ('transactions', 'Transactions'), ('payout', 'Payout')], help_text='Type of data contained in the uploaded file.', max_length=16),
        ),
        migrations.AlterField(
            model_name='ingestionevent',
            name='filename',
            field=models.CharField(help_text='Original filename as uploaded by the user.', max_length=255),
        ),
        migrations.AlterField(
            model_name='ingestionevent',
            name='raw_content',
            field=models.TextField(help_text='Verbatim file content stored for audit and potential reprocessing.'),
        ),
        migrations.AlterField(
            model_name='ingestionevent',
            name='source',
            field=models.ForeignKey(help_text='System that produced this file.', on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_events', to='reconciler.source'),
        ),
        migrations.AlterField(
            model_name='ingestionevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', help_text='Outcome of the ingestion attempt.', max_length=16),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.ForeignKey(help_text='Currency the invoice is denominated in.', on_delete=django.db.models.deletion.PROTECT, to='reconciler.currency'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(help_text='Customer this invoice was issued to.', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='reconciler.customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(help_text='Payment due date.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='force_close_note',
            field=models.TextField(blank=True, help_text='Mandatory reason when an admin force-closes an invoice without full payment.', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='force_closed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the invoice was force-closed.', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='force_closed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who force-closed this invoice.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='force_closed_invoices', to='reconciler.responsible'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='ingestion_event',
            field=models.ForeignKey(help_text='Upload event that created or last updated this invoice.', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='reconciler.ingestionevent'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(help_text='Business-key from the source CRM, e.g. INV-2026-0001 or CN-2026-0001.', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(help_text='Date the invoice was issued.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='source',
            field=models.ForeignKey(blank=True, help_text='System that produced this invoice.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='reconciler.source'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('force_closed', 'Force Closed')], default='open', help_text='Derived from matched allocations — do not set directly. Use recompute_status().', max_length=16),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, help_text='Sum of line items before tax.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, help_text='Total tax amount. Negative for credit notes.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='Amount the customer owes (subtotal + tax). Negative for credit notes.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('credit_note', 'Credit Note')], default='invoice', help_text='Invoice reduces receivables; credit note is a negative amount that reduces what the customer owes.', max_length=16),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Line total including tax (quantity × unit_price × (1 + tax_rate)).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='description',
            field=models.CharField(help_text='Service or product description as it appears on the invoice.', max_length=512),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='invoice',
            field=models.ForeignKey(help_text='Invoice this line belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='reconciler.invoice'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='line_id',
            field=models.CharField(help_text='Line item identifier from the source system.', max_length=64),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, help_text='Number of units.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, help_text='Tax rate as a decimal, e.g. 0.17 for 17% Luxembourg VAT.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit before tax.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='match',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, help_text='Portion of the transaction amount allocated to this invoice. For consolidated splits this is a fraction of the total.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='match',
            name='confidence_score',
            field=models.DecimalField(decimal_places=2, help_text='Engine confidence 0.0–1.0. ≥0.85 → auto_matched; <0.85 → needs_review.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='match',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Invoice being paid by this match. Null for noise, duplicate, and unresolved needs_review records.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='reconciler.invoice'),
        ),
        migrations.AlterField(
            model_name='match',
            name='locked_by_user',
            field=models.BooleanField(default=False, help_text='When True, the engine will never overwrite this match. Set on every manual action.'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('exact', 'Exact'), ('partial', 'Partial'), ('consolidated', 'Consolidated'), ('fx', 'FX'), ('credit_note', 'Credit Note'), ('payout', 'Payout'), ('noise', 'Noise'), ('duplicate', 'Duplicate'), ('prepayment', 'Prepayment')], help_text='Which matching rule and pattern produced this record.', max_length=16),
        ),
        migrations.AlterField(
            model_name='match',
            name='note',
            field=models.TextField(blank=True, help_text="Engine reason (e.g. 'Fuzzy counterparty match score=0.82') or reviewer comment.", null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='payout_line',
            field=models.ForeignKey(blank=True, help_text='Stripe PayoutLine this match was created from. Set only for payout-type matches.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='reconciler.payoutline'),
        ),
        migrations.AlterField(
            model_name='match',
            name='performed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last manual action.', null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='performed_by',
            field=models.ForeignKey(blank=True, help_text='User who last manually changed this match status.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_matches', to='reconciler.responsible'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('auto_matched', 'Auto Matched'), ('needs_review', 'Needs Review'), ('confirmed', 'Confirmed'), ('manually_matched', 'Manually Matched'), ('rejected', 'Rejected'), ('unrelated', 'Unrelated')], help_text='Current review state. auto_matched and confirmed are considered reconciled.', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='transaction',
            field=models.ForeignKey(help_text='Bank transaction this match belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='reconciler.transaction'),
        ),
        migrations.AlterField(
            model_name='payoutline',
            name='charge_id',
            field=models.CharField(help_text='Stripe charge, refund, or payout ID (ch_..., rf_..., cb_..., po_...).', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='payoutline',
            name='customer_name',
            field=models.CharField(help_text='Customer name as reported by Stripe.', max_length=256),
        ),
        migrations.AlterField(
            model_name='payoutline',
            name='fee',
            field=models.DecimalField(decimal_places=2, help_text='Stripe processing fee. Zero for refunds and chargebacks.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payoutline',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount before Stripe fees. Negative for refunds and chargebacks.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payoutline',
            name='ingestion_event',
            field=models.ForeignKey(help_text='Upload event that created this payout line.', on_delete=django.db.models.deletion.PROTECT, related_name='payout_lines', to='reconciler.ingestionevent'),
        ),
        migrations.AlterField(
            model_name='payoutline',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount actually credited to the bank account (gross minus fee). Used as allocated_amount on the Match.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payoutline',
            name='raw_invoice_id',
            field=models.CharField(blank=True, help_text='Invoice ID from the Stripe CSV invoice_id column. Null for refunds and chargebacks.', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='payoutline',
            name='transaction',
            field=models.ForeignKey(help_text='Parent bank transaction that received this Stripe payout.', on_delete=django.db.models.deletion.CASCADE, related_name='payout_lines', to='reconciler.transaction'),
        ),
        migrations.AlterField(
            model_name='payoutline',
            name='type',
            field=models.CharField(choices=[('charge', 'Charge'), ('refund', 'Refund'), ('chargeback', 'Chargeback'), ('payout', 'Payout')], help_text='Stripe line type. Charge lines are auto-matched; refund and chargeback lines go to needs_review.', max_length=16),
        ),
        migrations.AlterField(
            model_name='reconciliationrun',
            name='auto_matched_count',
            field=models.PositiveIntegerField(default=0, help_text='Transactions that reached auto_matched status in this run.'),
        ),
        migrations.AlterField(
            model_name='reconciliationrun',
            name='error_message',
            field=models.TextField(blank=True, help_text='Exception traceback if status=failed; empty otherwise.', null=True),
        ),
        migrations.AlterField(
            model_name='reconciliationrun',
            name='finished_at',
            field=models.DateTimeField(blank=True, help_text='Set when the run completes or fails.', null=True),
        ),
        migrations.AlterField(
            model_name='reconciliationrun',
            name='needs_review_count',
            field=models.PositiveIntegerField(default=0, help_text='Transactions that ended in needs_review and require human action.'),
        ),
        migrations.AlterField(
            model_name='reconciliationrun',
            name='skipped_locked_count',
            field=models.PositiveIntegerField(default=0, help_text='Transactions skipped because locked_by_user=True.'),
        ),
        migrations.AlterField(
            model_name='reconciliationrun',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', help_text='Current state of the run.', max_length=16),
        ),
        migrations.AlterField(
            model_name='reconciliationrun',
            name='total_processed',
            field=models.PositiveIntegerField(default=0, help_text='Number of transactions processed (locked records are excluded).'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='display_name',
            field=models.CharField(help_text='Full name shown in the audit trail.', max_length=128),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='role',
            field=models.CharField(choices=[('reviewer', 'Reviewer'), ('admin', 'Admin')], default='reviewer', help_text='Reviewers can confirm/reject matches; admins can force-close invoices and unlock matches.', max_length=16),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='user',
            field=models.OneToOneField(help_text='Linked Django user account.', on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='source',
            name='description',
            field=models.TextField(blank=True, help_text='Optional notes about this source, e.g. account number or API endpoint.', null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive sources are excluded from new ingestion but retained for audit.'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(help_text="Human-readable source name, e.g. 'ING Bank' or 'Stripe'.", max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('bank', 'Bank'), ('payment_processor', 'Payment Processor'), ('crm', 'CRM'), ('erp', 'ERP'), ('manual', 'Manual')], help_text='Category of the source system.', max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Signed amount: positive = credit (money received), negative = debit (money sent).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='counterparty',
            field=models.ForeignKey(blank=True, help_text='Normalized counterparty record. Null until the counterparty is linked to a customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='reconciler.counterparty'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(help_text='Currency the bank booked this transaction in.', on_delete=django.db.models.deletion.PROTECT, to='reconciler.currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(help_text='Value date of the bank movement (ISO 8601).'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, help_text='Free-text payment description from the bank. Mined by Rules 6, 7, and 8 for invoice IDs.', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ingestion_event',
            field=models.ForeignKey(help_text='Upload event that created or last updated this transaction.', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='reconciler.ingestionevent'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_duplicate',
            field=models.BooleanField(default=False, help_text='Set to True when the description starts with [RE-IMPORTED]. Routed to duplicate status by Rule 2.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='locked_by_user',
            field=models.BooleanField(default=False, help_text='When True, the reconciliation engine skips this transaction entirely. Set automatically on manual confirm/reject.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='raw_counterparty',
            field=models.CharField(help_text='Counterparty name exactly as it appeared in the bank export.', max_length=256),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reconciliation_status',
            field=models.CharField(choices=[('unprocessed', 'Unprocessed'), ('auto_matched', 'Auto Matched'), ('needs_review', 'Needs Review'), ('reconciled', 'Reconciled'), ('unrelated', 'Unrelated'), ('duplicate', 'Duplicate')], default='unprocessed', help_text='Current state in the reconciliation workflow. Derived by the engine; overridden by manual actions.', max_length=16),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Bank or system that produced this transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='reconciler.source'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='structured_reference',
            field=models.CharField(blank=True, help_text='Payment reference field from the bank (e.g. invoice ID or Stripe payout ID). Primary key for rule-based matching.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(help_text='Business-key from the bank export, e.g. TXN-0001.', max_length=32, unique=True),
        ),
    ]
